
export const INITIALIZE = "INITIALIZE";
export const POKEDEX_CRITERIA = "POKEDEX_CRITERIA";
export const SET_FILTER = "SET_FILTER";
export const DATA = "DATA";
export const TENFOUR_INITIALIZE = "INITIALIZE";
export const ACK_EFFECT = "ACK_EFFECT";
export const AUTOCOMPLETE_GENERATE = "AUTOCOMPLETE_GENERATE";